MnT_HealthWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('day_selector/', include('day_selector.urls')),
    path('admin/', admin.site.urls),
    path('calorie_calc/', include('calorie_calc.urls')),
    path('healthhacks/', include('healthhacks.urls')),
    path('', RedirectView.as_view(url='healthhacks/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

healthhacks/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard_view, name="dashboard"),
    path('login/', LoginView.as_view(), name="login_url"),
    path('register/', views.register_view, name="register_url"),
    path('logout/', LogoutView.as_view(next_page='dashboard'), name="logout"),
    path('dashboard/edit/', views.edit_profile, name="edit_profile")
]

forms/forms.py
from django import forms
from django.utils.safestring import mark_safe


class DayForm(forms.Form):
    day = forms.IntegerField(
        label=mark_safe('Type how many days of week you would like to exercise (1 - 6)'),
        max_value=6,
        min_value=1
    )


class CalorieForm(forms.Form):
    age = forms.IntegerField(label='Age (1-100):', help_text="", max_value=100, min_value=1, )
    weight = forms.IntegerField(help_text='Enter weight (lbs).', max_value=600, min_value=50)
    height = forms.IntegerField(help_text='Enter height (inches).', max_value=120, min_value=30)

    GENDER_ID = (
        ('M', 'Male'),
        ('F', 'Female')
    )

    gender = forms.CharField(
        max_length=1,
        widget=forms.RadioSelect(choices=GENDER_ID),
        help_text='Enter gender.'
    )

    ACTIVITY_LEVEL = (
        ('s', 'Sedentary'),
        ('l', 'Light Activity'),
        ('m', 'Moderate Activity'),
        ('v', 'Very Active'),
        ('e', 'Extremely Active')
    )

    activity = forms.CharField(
        max_length=1,
        widget=forms.RadioSelect(choices=ACTIVITY_LEVEL),
        help_text='Select activity level:'
    )

    GOAL_WEIGHT = (
        ('l', 'Lose Weight'),
        ('m', 'Maintain'),
        ('g', 'Gain Weight')
    )

    goal = forms.CharField(
        max_length=1,
        widget=forms.RadioSelect(choices=GOAL_WEIGHT),
        help_text='Select your weight goal.'
    )


class EditProfileForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Health Hacks</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="bg-primary">
<div class="container-fluid bg-white">
    <header class="d-flex align-items-center justify-content-center justify-content-md-between py-3 sticky-top bg-white">
        <a href="/" class="d-flex align-items-center text-dark text-decoration-none"
           style="font-size: 30px; font-weight: bolder; padding: 5px">
            HealthHacks
        </a>

        <ul class="nav justify-content-center mb-md-0 nav-tabs">
            <li><a href="/" class="nav-link px-2 link-dark">Home</a></li>
            <li><a href="{% url 'calorie_index' %}" class="nav-link px-2 link-dark">Calorie Calculator™</a></li>
            <li><a href="{% url 'fitness_index' %}" class="nav-link px-2 link-dark">Fitness Planning™</a></li>
            <li><a href="{% url 'dashboard' %}" class="nav-link px-2 link-dark">Profile</a></li>
        </ul>

        <div class="text-end" style="align-items: center">
            {% if user.is_authenticated %}
                <a class="me-2"
                   style="font-size: 25px; padding: 5px; color:black; text-decoration-line: none; vertical-align: middle"
                   href="{% url 'dashboard' %}">{{ user.username }}</a>
                <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-outline-primary me-2" href="{% url 'login_url' %}">Login</a>
                <a class="btn btn-primary" href="{% url 'register_url' %}">Sign-up</a>
            {% endif %}
        </div>
    </header>
</div>
{% block content %}{% endblock %}
</body>
</html>

templates/dashboard.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="mt-3" style="border-radius: 10px; background: rgba(0,0,0,0.67); padding: 30px; margin: 100px 30px 0 30px">
        <h1 class="text-center">Welcome,
            {% if first_name %}
                {{ first_name }} {{ last_name }}
            {% else %}
                user {{ user.username }}
            {% endif %}
        </h1>
        <ul class="list-unstyled">
            <li class="my-2"><strong>First Name:</strong> {{ first_name }}</li>
            <li class="my-2"><strong>Last Name:</strong> {{ last_name }}</li>
            <li class="my-2"><strong>Email:</strong> {{ email }}</li>
            <li class="my-2"><strong>Calorie Count:</strong>
                {% if calorie_count %}
                    <span style="color: #3eff91">{{ calorie_count }}</span>
                {% else %}
                    <a class="profile_link" href="{% url 'calorie_index' %}"> Get your Calorie Count!</a>
                {% endif %}</li>
            <li class="my-2"><strong>Fitness Plan:</strong>
                {% if fitness_plan %}
                    {{ fitness_plan }}
                {% else %}
                    <a class="profile_link" href="{% url 'fitness_index' %}"> Get your Fitness Plan!</a>
                {% endif %}
            </li>
            <li class="my-2" style="padding-top: 30px">
                <a class="btn btn-light" href="{% url 'edit_profile' %}"> Edit your profile</a>
            </li>
        </ul>
    </div>
{% endblock %}

templates/edit_profile.html
{% extends 'base_generic.html' %}
{% block content %}
    <div class="container-fluid mt-3 text-center">
        <h1 class=""> Edit your profile</h1>
        <form class="form" method="post">
            {% csrf_token %}
            <ul class="form" style="list-style: none">
                <li class="my-3">
                    <label for="id_first_name"><strong>First name:</strong></label> {{ form.first_name }}
                </li>
                <li class="my-3">
                    <label for="id_last_name"><strong>Last name:</strong></label> {{ form.last_name }}
                </li>
                <li class="my-3">
                    <label for="id_email"><strong>Email:</strong></label> {{ form.email }}
                </li>
            </ul>
            <input class="btn btn-dark" type="submit" value="Edit Profile">
        </form>
    </div>
{% endblock %}

templates/index.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 class="d-flex justify-content-center" style="font-size: 70px; height: 200px; align-items: center">
        {% if user.username %}
            Welcome, {{ user.username }}
        {% else %}
            Welcome! Please login.
        {% endif %}
    </h1>
    <h2 class="d-flex justify-content-center" style="height: 100px">Please select one of the options below.</h2>
    <div class="row text-center m-auto">
        <div class="col my-auto">
            <div class="card rounded-3 m-auto">
                <a class="rounded-3" href="{% url 'calorie_index' %}"><span class="card-item">Calorie Calculator™</span></a>
            </div>
        </div>
        <div class="col my-auto">
            <div class="card rounded-3 m-auto">
                <a class="rounded-3" href="{% url 'fitness_index' %}"><span
                        class="card-item">Fitness Planning™</span></a>
            </div>
        </div>
        <div class="col my-auto">
            <div class="card rounded-3 m-auto">
                <a class="rounded-3" href="{% url 'dashboard' %}"><span class="card-item">Dashboard</span></a>
            </div>
        </div>
    </div>
{% endblock %}

templates/just_navbar.html
{% extends 'base_generic.html' %}