MnT_HealthWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('day_selector/', include('day_selector.urls')),
    path('admin/', admin.site.urls),
    path('calorie_calc/', include('calorie_calc.urls')),
    path('healthhacks/', include('healthhacks.urls')),
    path('', RedirectView.as_view(url='healthhacks/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

calorie_calc/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='calorie_index'),
    path('complete', views.calculate_success, name='calorie_complete')
]

healthhacks/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard_view, name="dashboard"),
    path('login/', LoginView.as_view(), name="login_url"),
    path('register/', views.register_view, name="register_url"),
    path('logout/', LogoutView.as_view(next_page='dashboard'), name="logout"),
    path('dashboard/edit/', views.edit_profile, name="edit_profile")
]

calorie_calc/models.py
from django.db import models
from django.urls import reverse
import backend.calorie_calc


# Create your models here.

forms/forms.py
from django import forms
from django.utils.safestring import mark_safe


class DayForm(forms.Form):
    day = forms.IntegerField(
        label=mark_safe('Type how many days of week you would like to exercise (1 - 6)'),
        max_value=6,
        min_value=1
    )


class CalorieForm(forms.Form):
    age = forms.IntegerField(label='Age (1-100):', help_text="", max_value=100, min_value=1, )
    weight = forms.IntegerField(help_text='Enter weight (lbs).', max_value=600, min_value=50)
    height = forms.IntegerField(help_text='Enter height (inches).', max_value=120, min_value=30)

    GENDER_ID = (
        ('M', 'Male'),
        ('F', 'Female')
    )

    gender = forms.CharField(
        max_length=1,
        widget=forms.RadioSelect(choices=GENDER_ID),
        help_text='Enter gender.'
    )

    ACTIVITY_LEVEL = (
        ('s', 'Sedentary'),
        ('l', 'Light Activity'),
        ('m', 'Moderate Activity'),
        ('v', 'Very Active'),
        ('e', 'Extremely Active')
    )

    activity = forms.CharField(
        max_length=1,
        widget=forms.RadioSelect(choices=ACTIVITY_LEVEL),
        help_text='Select activity level:'
    )

    GOAL_WEIGHT = (
        ('l', 'Lose Weight'),
        ('m', 'Maintain'),
        ('g', 'Gain Weight')
    )

    goal = forms.CharField(
        max_length=1,
        widget=forms.RadioSelect(choices=GOAL_WEIGHT),
        help_text='Select your weight goal.'
    )


class EditProfileForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)

calorie_calc/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from forms import forms
from backend import calorie_calc
from healthhacks.models import User, CalorieCalc
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='/healthhacks/login/')
def index(request):
    user = list(User.objects.filter(username__exact=request.user.username))[0]
    calculated = bool(user.calorie_count)

    calorie_count = 0
    if calculated:
        calorie_count = user.calorie_count.get_goal()

    if request.method == "POST":
        form = forms.CalorieForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            if user.calorie_count:
                user.calorie_count.delete()

            calorie = CalorieCalc(age=data['age'], weight=data['weight'], height=data['height'], gender=data['gender'],
                                  activity=data['activity'], goal=data['goal'])
            calorie.save()
            user.calorie_count = calorie
            user.save()
            return redirect('calorie_complete')
    else:
        form = forms.CalorieForm()

    context = {
        'form': form,
        'calculated': calculated,
        'calorie_count': calorie_count,
    }

    return render(request, 'calorie_calc/index.html', context=context)


def day_selected(request, day):
    if 1 <= day <= 6:
        return HttpResponse("%s" % day)
    else:
        return HttpResponse("Invalid number of days")


def calculate_success(request):
    user = list(User.objects.filter(username__exact=request.user.username))[0]
    cal = user.calorie_count

    context = {
        'calorie_goal': cal.get_goal(),
    }

    return render(request, 'calorie_calc/complete.html', context=context)

calorie_calc/templates/calorie_calc/complete.html
{% extends 'base_generic.html' %}
{% block content %}
    <div class="container-fluid mt-3 text-center">
        <h1 style="height: 100px;">Calorie Calculated!</h1>
        <p>Your required number of calories are: {{ calorie_goal }}</p>
    </div>
{% endblock %}

calorie_calc/templates/calorie_calc/index.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="container-fluid mt-3 text-center">
        {% if calculated %}
            <h2 style="height: auto; ">You already have a calorie count! Submitting a new calculation will reset your
                count.</h2>
            <h3 style="height: 100px">Your current calorie count: <span
                    style="color: #3eff91;">{{ calorie_count }}</span></h3>
        {% else %}
            <h2 style="height: auto;">Enter your data and get your calorie count with our Calculator!</h2>
        {% endif %}

        <h4 style="margin-bottom: 30px">Calorie Calculator™</h4>
        <form action="/calorie_calc/" method="post" style="display: block">
            {% csrf_token %}
            <ul class="form" style="list-style: none">
                <li>
                    <label for="id_age"><strong>Age (1-100):</strong></label> {{ form.age }}
                </li>
                <li>
                    <label for="id_weight"><strong>Weight (lbs):</strong></label> {{ form.weight }}
                </li>
                <li>
                    <label for="id_height"><strong>Height (inches):</strong></label> {{ form.height }}
                </li>
                <li>
                    <label for="id_gender"><strong>Gender:</strong></label> {{ form.gender }}
                </li>
                <li>
                    <label for="id_activity"><strong>Activity Level:</strong></label> {{ form.activity }}
                </li>
                <li>
                    <label for="id_goal"><strong>What is your goal?</strong></label> {{ form.goal }}
                </li>
            </ul>
            <input type="submit" value="Submit">
        </form>
    </div>
    <footer class="text-center" style="position: absolute; bottom: 0; align-content: center; margin-left: 20px">
        <p>Source: <a target="_blank" href="https://www.checkyourhealth.org/eat-healthy/cal_calculator.php">checkyourhealth.org</a>
        </p>
    </footer>
{% endblock %}